[package]
name = "evolutionary_image_registration"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
bevy_flycam = "*"
image = "0.25.5"
kiddo = "5.0.3"
nalgebra = "0.33.2"
rand = "0.8.5"
rayon = "1.10.0"